//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoPaciente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int idHistorial { get; set; }
        public Nullable<int> idExamen { get; set; }
        public Nullable<int> idFarmaco { get; set; }
        public string doctor { get; set; }
        public Nullable<int> rutPaciente { get; set; }
        public Nullable<System.DateTime> fechaIngresoFarmaco { get; set; }
        public Nullable<int> rangoDeExamen { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<System.DateTime> proximaFecha { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual TipoDeSeguimiento TipoDeSeguimiento { get; set; }
    }
}
