//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoPaciente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntasItems
    {
        public int idPreguntasItems { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> codItems { get; set; }
    
        public virtual ItemsPreventivos ItemsPreventivos { get; set; }
    }
}
