//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoPaciente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string usuario1 { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> tipoUsuario { get; set; }
        public string hash { get; set; }
    
        public virtual TipoUsuario TipoUsuario1 { get; set; }
    }
}
